# NUMPY

## 1. Introduction to NumPy

NumPy (Numerical Python) is a Python library used for scientific computing and numerical operations. It provides support for:
- Large multi-dimensional arrays
- Mathematical operations
- Linear algebra
- Random number generation
- Statistical operations
The main object of NumPy is ndarray (N-dimensional array).

### Why NumPy is faster than Python lists?
- Uses C language implementation internally
- Stores data in continuous memory
- Performs vectorized operations

**Example :**

In [1]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a + b)

[ 6  8 10 12]


In normal Python lists this would require loops.

## 2. Installing NumPy

If NumPy is not installed: Run `pip install numpy` in terminal

Import NumPy: `import numpy as np`

`np` is just an alias used by convention.

## 3. Creating NumPy Arrays
### 3.1 Creating Array from Python List

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


### 3.2 Creating 2D Array

In [3]:
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


## 4. Dimensions of Array

| Dimension | Example           |
| --------- | ----------------- |
| 1D        | `[1,2,3]`         |
| 2D        | `[[1,2],[3,4]]`   |
| 3D        | `[[[1,2],[3,4]]]` |


In [4]:
arr = np.array([1,2,3])
print(arr.ndim)

1


## 5. Array Attributes

Important attributes of NumPy array:

| Attribute | Description          | 
| --------- | -------------------- |
| ndim      | number of dimensions |
| shape     | size of array        |
| size      | total elements       |
| dtype     | datatype             |
| itemsize  | memory size          |


In [5]:
# Example:  
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

2
(2, 3)
6
int64
8


## 6. Creating Special Arrays
### 6.1 Zeros Array

Creates array filled with zeros.

In [6]:
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


### 6.2 Ones Array

In [7]:
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 6.3 Identity Matrix

In [8]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 6.4 Arange Function
Works like range().

In [9]:
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


### 6.5 Linspace
Creates equally spaced numbers.

In [10]:
arr = np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


## 7. Array Indexing

Access elements using index.

**Example:**

In [11]:
arr = np.array([10,20,30,40])

print(arr[0])
print(arr[2])

10
30


**2D Indexing**

In [12]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr[0,1])

2


## 8. Array Slicing

Used to extract part of array.

Syntax : `array[start:end]`

In [13]:
arr = np.array([1,2,3,4,5,6])

print(arr[1:4])


[2 3 4]


**2D Slicing**

In [14]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr[:,1])

[2 5]


## 9. Reshaping Arrays

Changes the shape of array.

**Example:**

In [15]:
arr = np.array([1,2,3,4,5,6])

new_arr = arr.reshape(2,3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


## 10. Mathematical Operations

NumPy performs element-wise operations.

**Example**

In [16]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


## 11. Aggregate Functions

Used to perform statistical operations.

| Function  | Purpose            |
| --------- | ------------------ |
| np.sum()  | sum                |
| np.mean() | average            |
| np.max()  | maximum            |
| np.min()  | minimum            |
| np.std()  | standard deviation |

**Example :** 

In [17]:
arr = np.array([10,20,30,40])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))

100
25.0
40


## 12. Random Numbers in NumPy

NumPy can generate random numbers.

**Example:**

In [18]:
arr = np.random.rand(3)
print(arr)

[0.1552133  0.43962339 0.03811166]


Random integers:

In [19]:
arr = np.random.randint(1,10,5)
print(arr)

[5 3 4 4 9]


## 13. Copy vs View

**Copy**

Creates new array.

In [20]:
a = np.array([1,2,3])
b = a.copy()

b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


**View**

Shares memory.

In [21]:
a = np.array([1,2,3])
b = a.view()

b[0] = 100

print(a)
print(b)

[100   2   3]
[100   2   3]


## 14. Iterating Through Arrays

**Example :**

In [22]:
arr = np.array([1,2,3,4])

for x in arr:
    print(x)

1
2
3
4


## 15. Example (Student Marks Analysis)

**Example :** 

In [23]:
import numpy as np

marks = np.array([70,80,90,60,75])

print("Average:", np.mean(marks))
print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))

Average: 75.0
Maximum: 90
Minimum: 60


## 16. Advantages of NumPy

- Faster than Python lists

- Less memory usage

- Supports large datasets

- Provides powerful mathematical functions

- Used in Machine Learning, Data Science, AI


## 17. Real World Uses of NumPy

**NumPy is used in:**

- Machine Learning

- Image Processing

- Data Science

- Artificial Intelligence

- Scientific Computing

**Popular libraries built on NumPy:**

- Pandas

- TensorFlow

- Scikit-Learn

- Matplotlib